### ISSUE TITLE
No ASCII compatibility

### ISSUE THREAD

**Issue by itschleemilch** [littleblah/senior-engineer-checklist#5]
Hi,

Thanks for sharing this list. I noticed unicode quotation marks in

4 - Question everything and ask “why” repetitively until you get to the root of problems and situations.

which caused trouble when importing the CSV into Excel. In comparison, the following item has ASCII quotation marks:

52 - Document "why" more than "how"

I propose to change all quotation marks to " to make the file ASCII compatible.

**Comment by viveksri15** [comment]
Thanks. Doing it now.

**Comment by littleblah** [comment]
Thanks. Doing it now.
